import { useState, useEffect, useContext } from "react";
import Header from "../../components/Header";
import "./style.css";
import BackgroundContext from "../../components/BackgroundContext";

const AboutPage = () => {
  const backgroundCtx = useContext(BackgroundContext);
  const { background, setBackground } = backgroundCtx;

  useEffect(() => {
    document.title = "About";
    setBackground("blue-mountain");
  }, []);

  return (
    <div className={background}>
      <Header />
      <div className="container about-container">
        <div className="about-header">
          <h1>About Weather Hub</h1>
        </div>
        <div className="introduction">
          <p>
            Weather Hub is a one-stop shop for all your weather-related needs.
            We provide accurate and up-to-date weather forecasts, news, and
            information, powered by the latest weather API technology and the
            New York Times.
          </p>
        </div>
        <div className="missions">
          <p>
            Our website is easy to use and navigate, and we offer a variety of
            features to help you stay informed about the weather, including:
          </p>
          <ul>
            <li>
              Current weather conditions for your location, as well as for any
              other location in the world.
            </li>
            <li>
              Hourly and daily forecasts for your location, so you can plan your
              day ahead of time.
            </li>
            <li>
              Severe weather alerts for your area, so you can stay safe in the
              event of a storm or other hazardous weather event.
            </li>
            <li>
              Weather news and articles from the New York Times, so you can stay
              informed about the latest weather developments around the world.
            </li>
          </ul>
        </div>
        <div className="about-commit">
          <p>
            We are committed to providing our users with the most accurate and
            up-to-date weather information possible. Our weather forecasts are
            generated by the latest weather API technology, which uses data from
            a variety of sources, including satellites, radar, and ground-based
            weather stations. We also use the latest forecasting models to
            predict future weather conditions.
          </p>
          <p>
            In addition to weather forecasts, we also offer a variety of other
            weather-related information, such as:
          </p>
        </div>
        <div className="about-commit-list">
          <ul>
            <li>
              Air quality data for your location, so you can be aware of the air
              quality and take steps to protect your health if necessary.
            </li>
            <li>
              Allergy forecasts for your location, so you can plan your day
              accordingly if you have allergies.
            </li>
            <li>
              Astronomy information, such as sunrise and sunset times, moon
              phases, and meteor showers.
            </li>
          </ul>
        </div>
        <div className="about-contact-us">
          We are always looking for ways to improve our website and make it more
          useful for our users. If you have any suggestions, please feel free to
          contact us.
        </div>
      </div>
    </div>
  );
};

export default AboutPage;
